plugins { id 'com.android.application' }
android {
    namespace 'org.abuh.questassistant'
    compileSdk 35
    defaultConfig {
        applicationId 'org.abuh.questassistant'
        minSdk 29
        targetSdk 32
        versionCode 1
        versionName '0.1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies { implementation 'androidx.webkit:webkit:1.12.1' }
